### ISSUE TITLE
Rekuire failed at lib/helpers/scanner.js:103

### ISSUE THREAD

**Issue by longlh** [nadav-dav/rekuire#10]
ambiguousFileNames[alias].push(realpath);
                                             ^

TypeError: Object function toString() { [native code] } has no method 'push' at insertPathToIndex (...node_modules/rekuire/lib/helpers/scanner.js:103:35)

This issue happens when I do a fresh clone of a working project.

**Comment by kaminskypavel** [comment]
@nadav-dav thanks for the fix man :+1: , just stumbled upon this issue on my prod :)
