### ISSUE TITLE
Rekuire helpers files issue from fresh install

### ISSUE THREAD

**Issue by ndongoli** [nadav-dav/rekuire#12]
ERROR in ./~/rekuire/lib/helpers/scanner.js
Module not found: Error: Cannot resolve module 'fs' in /Users/ady.ngom/Development/react/github-notetaker/node_modules/rekuire/lib/helpers
 @ ./~/rekuire/lib/helpers/scanner.js 3:9-22

ERROR in ./~/rekuire/lib/helpers/findBase.js
Module not found: Error: Cannot resolve module 'fs' in /Users/ady.ngom/Development/react/github-notetaker/node_modules/rekuire/lib/helpers
 @ ./~/rekuire/lib/helpers/findBase.js 1:9-22

This is after a fresh npm install

**Comment by nadav-dav** [comment]
what version of node are you running?
it seems that it fails to find the `fs` module that is part of node's core (so so strange..)

**Comment by ndongoli** [comment]
I just updated to v0.12.2 today (5 min ago). I'll rerun webpack right now and see if the error is still here.

**Comment by ndongoli** [comment]
Still the same error:

WARNING in ./~/rekuire/lib/main.js
Critical dependencies:
11:10-53 the request of a dependency is an expression
 @ ./~/rekuire/lib/main.js 11:10-53

ERROR in ./~/rekuire/lib/helpers/scanner.js
Module not found: Error: Cannot resolve module 'fs' in /Users/ady.ngom/Development/react/github-notetaker/node_modules/rekuire/lib/helpers
 @ ./~/rekuire/lib/helpers/scanner.js 3:9-22

ERROR in ./~/rekuire/lib/helpers/findBase.js
Module not found: Error: Cannot resolve module 'fs' in /Users/ady.ngom/Development/react/github-notetaker/node_modules/rekuire/lib/helpers
 @ ./~/rekuire/lib/helpers/findBase.js 1:9-22

**Comment by nadav-dav** [comment]
oh! i think i got it! :D
do you happen to run it in the browser? `rekuire` is designed to be used only on the server.

my guess, it that somehow webpack is scanning it and aggregating it to your output file, that then loads on the client side..

what do you think? can this be the case?

**Comment by ndongoli** [comment]
Yes that's very possible I'm using it on a react project and for the first time on a client only setup. You are probably right. With the advent of Browserify and webpack I thought I would have access to all my favorite packages client side. No worries thanks for checking and thanks for an awesome package :)

**Comment by nadav-dav** [comment]
I love React! :+1: 
I'm glad I could help!
